"""Runs *inside* FreeCAD (freecadcmd) to build nyxilab_macropad.FCStd.

Started by ``export.export_freecad`` with QT_QPA_PLATFORM=offscreen so the
GUI layer exists (needed to store colours).  Inputs come from the JSON job
file named in $MACROPAD_FC_JOB.
"""

import json
import os

import FreeCAD as App
import Part

job = json.load(open(os.environ["MACROPAD_FC_JOB"]))
gui = False
try:
    import FreeCADGui as Gui

    Gui.showMainWindow()
    gui = True
except Exception as exc:  # colours are skipped without a GUI layer
    print("FreeCAD GUI layer unavailable:", exc)

doc = App.newDocument("nyxilab_macropad", hidden=True)  # no 3D view: offscreen Qt has no OpenGL
printed = doc.addObject("App::DocumentObjectGroup", "Printed_parts")
for p in job["parts"]:
    obj = doc.addObject("Part::Feature", p["name"])
    obj.Shape = Part.read(p["step"])
    obj.Label = p["name"]
    printed.addObject(obj)
    if gui:
        obj.ViewObject.ShapeColor = tuple(p["color"])

refs = doc.addObject("App::DocumentObjectGroup", "Reference_components")
try:
    if gui:
        import ImportGui

        before = set(o.Name for o in doc.Objects)
        ImportGui.insert(job["components_step"], doc.Name)
    else:
        import Import

        before = set(o.Name for o in doc.Objects)
        Import.insert(job["components_step"], doc.Name)
    for o in doc.Objects:
        if o.Name not in before and not o.InList:
            refs.addObject(o)
except Exception as exc:
    print("component import failed:", exc)

sheet = doc.addObject("Spreadsheet::Sheet", "Layout")
sheet.set("A1", "Generated by cad/macropad_cad (build123d) - edit params.py, not this file")
for i, (k, v) in enumerate(job["params"].items(), start=3):
    sheet.set(f"A{i}", str(k))
    sheet.set(f"B{i}", str(v))
doc.recompute()
doc.saveAs(job["out"])
os._exit(0)
